# Generated by Django 5.2.4 on 2025-07-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='in_use_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
