# Generated by Django 5.2.4 on 2025-07-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0003_machine_last_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='machine',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
